######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 3 09:33:21 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += prj.cpp
